[[main]]
  name = "홈"
  url = "/"
  weight = 1

[[main]]
  name = "쿠버네티스 강의"
  pageRef = "kubernetes"
  weight = 2

[[main]]
  name = "아카이브"
  pageRef = "archives"
  weight = 3

[[main]]
  name = "카테고리"
  pageRef = "categories"
  weight = 4

[[main]]
  name = "소개"
  pageRef = "about"
  weight = 5
