colorScheme = "noir"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

disableImageOptimization = false
disableTextInHeader = false

fingerprintAlgorithm = "sha512"

[header]
  layout = "fixed"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "hero"
  homepageImage = ""
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showRelatedContent = true
  relatedContentLimit = 3
  math = true

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  groupByYear = true
  cardView = true

[taxonomy]
  showTermCount = true
  showBreadcrumbs = false
  cardView = true

[term]
  showBreadcrumbs = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
